name: Terraform Blob Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}

    steps:
    - name:  Checkout Code
      uses: actions/checkout@v3

    - name:  Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name:  Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name:  Terraform Init
      run: terraform init -reconfigure

    - name:  Terraform Validate
      run: terraform validate

    - name:  Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"

    - name:  Terraform Apply
      run: terraform apply -auto-approve -var-file="terraform.tfvars"
